### ISSUE TITLE
Is openjdk-7-jdk needed in the VM?

### ISSUE THREAD

**Issue by emalgorithm** [chadlung/vagrant-kafka#1]
Why would we need openjdk-7-jdk in the VM? It is currently being downloaded, but as far as I can see it is not used.

**Comment by chadlung** [comment]
Both Kafka and Zookeeper are Java based applications.

**Comment by emalgorithm** [comment]
Why doesn't the [Documentation](https://kafka.apache.org/documentation.html#quickstart) mention it then?

**Comment by chadlung** [comment]
They do: https://kafka.apache.org/documentation.html#java

**Comment by emalgorithm** [comment]
I see, thanks!
